// This file is auto-generated by `npx convex dev`. Do not edit manually.
// Stub for TypeScript until Convex is initialized.

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const api: any = {};
export default api;
export { api };
