// This file is auto-generated by `npx convex dev`. Do not edit manually.
// Stub for TypeScript until Convex is initialized.
export const query = (config: unknown) => config;
export const mutation = (config: unknown) => config;
export const action = (config: unknown) => config;
export const internalQuery = (config: unknown) => config;
export const internalMutation = (config: unknown) => config;
export const internalAction = (config: unknown) => config;
